# Pré-processamento dos dados do Vivino para input no Tableau

Este notebook descreve o passo-a-passo da preparação dos dados que baixei do meu perfil no Vivino em Junho de 2020, com o objetivo de construir um dashboard no Tableau para fins de análise exploratória.

Este trabalho foi realizado em R. Para a instalação do kernel do R no Jupyter, o seguintes tutoriais podem ser úteis:

- https://medium.com/@kyleake/how-to-install-r-in-jupyter-with-irkernel-in-3-steps-917519326e41
- https://richpauloo.github.io/2018-05-16-Installing-the-R-kernel-in-Jupyter-Lab/

O Vivino é um app onde os usuários podem catalogar, dar uma nota e escrever um review para os vinhos que degusta a partir do upload de uma foto do rótulo. Mais informações podem ser obtidas na Wikipedia: https://en.wikipedia.org/wiki/Vivino

Para realizar esta tarefa, optei por utilizar a biblioteca dplyr do R:

In [1]:
library(dplyr)

Warning message:
"package 'dplyr' was built under R version 3.6.3"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



Em seguida carreguei o arquivo de interesse (full_wine_list.csv) que baixei do Vivino e verifiquei a sua estrutura e 
características gerais:

In [2]:
dados <- read.csv(file.choose())

head(dados,1)
str(dados)
summary(dados)




Winery  Wine.name             Vintage Region            Country
1 Matetic EQ Granite Pinot Noir 2014    Casablanca Valley Chile  
  Regional.wine.style Average.rating Scan.date           Scan.Review.Location
1 Chilean Pinot Noir  3.97           2020-06-16 14:36:21 NA                  
  Your.rating Your.review Personal.Note Wine.type Drinking.Window
1 4                       NA            Red Wine  NA             
  Wishlisted.date Cellar.count Link.to.wine                          
1 NA              NA           https://www.vivino.com/wines/160547630
  Label.image                                                 Wine.price
1 https://images.vivino.com/labels/FGBh-GGJQJG3hZNbVSZljw.jpg

'data.frame':	87 obs. of  19 variables:
 $ Winery              : Factor w/ 78 levels "Alamos","Albert Bichot",..: 50 3 61 38 8 73 9 23 25 75 ...
 $ Wine.name           : Factor w/ 75 levels "Alta Malbec",..: 27 32 67 24 53 9 68 74 8 65 ...
 $ Vintage             : int  2014 2018 2016 2017 2014 8888 2012 2018 2008 2017 ...
 $ Region              : Factor w/ 49 levels "","Aconcagua Valley",..: 14 41 14 46 11 36 30 3 48 25 ...
 $ Country             : Factor w/ 13 levels "","Argentina",..: 4 2 4 2 12 3 12 9 5 4 ...
 $ Regional.wine.style : Factor w/ 36 levels "","Argentinian Cabernet Sauvignon",..: 22 4 22 2 14 10 15 29 1 20 ...
 $ Average.rating      : num  3.97 3.41 3.62 3.39 3.54 3.27 3.82 3.63 3.46 3.54 ...
 $ Scan.date           : Factor w/ 87 levels "","2014-11-09 22:25:45",..: 87 86 85 84 83 82 81 80 79 78 ...
 $ Scan.Review.Location: logi  NA NA NA NA NA NA ...
 $ Your.rating         : num  4 3 NA 3 3.5 3 4 3.5 3 3 ...
 $ Your.review         : Factor w/ 8 levels "","!!!","Ã\200 su

                  Winery                             Wine.name     Vintage    
 TarapacÃ¡           : 3   Cabernet Sauvignon             : 5   Min.   :2008  
 Alfredo Roca        : 2   Pinot Noir                     : 4   1st Qu.:2012  
 Casillero del Diablo: 2   Gran Reserva Cabernet Sauvignon: 3   Median :2014  
 CousiÃ±o-Macul      : 2   Fincas Malbec                  : 2   Mean   :2263  
 D.V. Catena         : 2   Malbec                         : 2   3rd Qu.:2016  
 Luigi Bosca         : 2   Reserva Malbec                 : 2   Max.   :9999  
 (Other)             :74   (Other)                        :69                 
               Region            Country  
 Mendoza          :13   Chile        :28  
 Colchagua Valley : 8   Argentina    :26  
 Maipo Valley     : 5   France       : 9  
 Lujan de Cuyo    : 4   Italy        : 5  
 Casablanca Valley: 3   Spain        : 4  
 Central Valley   : 3   United States: 4  
 (Other)          :51   (Other)      :11  
                     Reg

O resultado mostra que várias colunas do arquivo baixado não terão utilidade na minha análise. 

Por exemplo, colunas como "Drinking.Window","Scan.Review.Location", dentre outras não possuem valor em nenhum dos registros, pois são campos que não preenchi quando fiz a avaliação dos rótulos.

No trecho de código abaixo retirei todas as colunas que não são relevantes:

In [3]:
dados <- dados %>% 
  select(-c(Scan.Review.Location,Your.review,Personal.Note,Drinking.Window,
            Wishlisted.date,Cellar.count,Wine.price))

O próximo passo é verificar a qualidade dos dados das colunas remanescentes, bem como corrigir possíveis inconsistências.

Vamos começar com a coluna "Country": o comando summary nos informou a existência de 17 países distintos e vamos verificar quais são eles:

In [4]:
dados %>% distinct(Country) %>% arrange(Country)

Country      
1               
2  Argentina    
3  Brazil       
4  Chile        
5  France       
6  Germany      
7  Italy        
8  New Zealand  
9  Portugal     
10 South Africa 
11 Spain        
12 United States
13 Uruguay

Como um dos valores únicos de país está em branco, vamos verificar quantas entradas são afetadas:

In [5]:
dados %>% filter(Country=="")

Winery     Wine.name                        Vintage Region Country
1 Steakhouse Brett Favre's Cabernet Sauvignon 2016                  
  Regional.wine.style Average.rating Scan.date           Your.rating Wine.type
1                     3.13           2017-09-30 22:35:10 NA          Red Wine 
  Link.to.wine                          
1 https://www.vivino.com/wines/154556162
  Label.image                                                
1 https://images.vivino.com/labels/hmTFCi4SSDiVv5RJ6w-odQ.jpg

Apenas 1 das entradas foi afetada e, por inspeção manual deste vinho no Vivino, verifiquei que trata-se de um rótulo produzido na Argentina. Desta forma, vamos corrigir o registro:

In [6]:
dados <- dados %>%
  mutate(Country=replace(Country,which(Country==""),"Argentina"))

Em seguida vamos verificar o campo "Vintage", pois o comando Summary indicou que o valor máximo deste campo é 9999, o que não é condizente com o ano de safra de um vinho. Vamos verificar os valores únicos:

In [7]:
dados %>% distinct(Vintage) %>% arrange(Vintage)

Vintage
1  2008   
2  2009   
3  2010   
4  2011   
5  2012   
6  2013   
7  2014   
8  2015   
9  2016   
10 2017   
11 2018   
12 8888   
13 9999

Em seguida vamos buscar as entradas afetadas pelos valores 8888 e 9999:

In [8]:
dados %>% filter(Vintage == 8888 | Vintage == 9999)

Winery                          Wine.name             Vintage
1 VinÃ­cola Hermann               Bossa No. 1 Brut      8888   
2 I Castelli di Romeo e Giulietta Bardolino             9999   
3 Col Brioso                      Gran CuvÃ©e Extra Dry 8888   
  Region            Country Regional.wine.style Average.rating
1 Rio Grande do Sul Brazil  Brazilian Sparkling 3.27          
2 Bardolino         Italy   Northern Italy Red  3.23          
3 Prosecco          Italy   Italian Prosecco    3.58          
  Scan.date           Your.rating Wine.type
1 2020-01-10 00:34:27 3           Sparkling
2 2019-03-28 18:53:08 3           Red Wine 
3 2018-12-21 23:03:12 3           Sparkling
  Link.to.wine                          
1 https://www.vivino.com/wines/2183905  
2 https://www.vivino.com/wines/4433694  
3 https://www.vivino.com/wines/152392933
  Label.image                                                
1 https://images.vivino.com/labels/iTw1X0jNSne-pOcf8Hmabg.jpg
2 https://images.vivino.com/labels/Kxjmg2jfQbq5w5XqNlcr3g.jpg
3 https://images.vivino.com/labels/jFay58HSQ6OhPJpUs9mxrw.jpg

Concluí que o valor 8888 está atrelado a espumantes e, para esta categoria,especificar a safra não é aplicável. Já o valor 9999 refere-se a um vinho tinto e, ao verificar manualmente no Vivino, não consegui encontrar a safra no rótulo. Deixei estes valores para serem tratados posteriormente no Tableau (utilizarei um Alias para substituí-los nos gráficos).

Os próximos campos a serem analisados são "Average.rating" e "Your.rating", pois uma das coisas que quero saber é se minhas avaliações são melhores ou piores que a média de avaliações do Vivino.

A saída do comando Summary mostrou que o campo "Average.rating" está ok, pois todos os valores estão presentes e contidos no intervalo de 0 a 5, nota mínima e máxima que pode ser dada a um rótulo, respectivamente. Já o "Your.rating" possui NAs e vamos verificar os registros afetados:

In [9]:
dados %>% filter(is.na(Your.rating))

Winery     Wine.name                        Vintage Region           
1 Sideways   Signature Series Pinot Noir      2016    Casablanca Valley
2 Los Riscos Cabernet Sauvignon               2016    Curico Valley    
3 Steakhouse Brett Favre's Cabernet Sauvignon 2016                     
4 TarapacÃ¡  Terroir El Rosal Pinot Noir      2013    Casablanca Valley
  Country   Regional.wine.style        Average.rating Scan.date          
1 Chile     Chilean Pinot Noir         3.62           2020-01-26 17:39:44
2 Chile     Chilean Cabernet Sauvignon 3.18           2018-01-27 20:46:44
3 Argentina                            3.13           2017-09-30 22:35:10
4 Chile     Chilean Pinot Noir         3.57           2016-03-05 19:17:50
  Your.rating Wine.type Link.to.wine                          
1 NA          Red Wine  https://www.vivino.com/wines/161911521
2 NA          Red Wine  https://www.vivino.com/wines/99118949 
3 NA          Red Wine  https://www.vivino.com/wines/154556162
4 NA          Red Wine  https://www.vivino.com/wines/7300440  
  Label.image                                                
1 https://images.vivino.com/labels/tN8KLpyRSoiMmYJ9F18Znw.jpg
2 https://images.vivino.com/labels/2wH7dxWsQJW7hhLu1mJk7Q.jpg
3 https://images.vivino.com/labels/hmTFCi4SSDiVv5RJ6w-odQ.jpg
4 https://images.vivino.com/labels/VD9ouAVNRTybvSP01AO9KQ.jpg

Verifiquei no Vivino que, de fato, minha avaliação não ficou registrada para estes rótulos. Visto que normalmente dou nota 3 nos vinhos que acho bons para o dia a dia e que, seu eu achasse algo especial nesses rótulos a ponto de elevar a nota, eu dificilmente teria deixado de registrar resolvi aplicar a nota 3 a todos eles.

In [10]:
table(dados$Your.rating)

dados <- dados %>%
  mutate(Your.rating=replace(Your.rating,which(is.na(Your.rating)),3))


1.5   3 3.5   4 4.5   5 
  1  41  18  17   5   1 

Por último analisei a qualidade do campo "Scan.date", pois pretendo filtrar as análises por ano de degustação:

In [11]:
dados %>% distinct(Scan.date)%>% arrange(Scan.date)

Scan.date          
1                      
2   2014-11-09 22:25:45
3   2014-12-24 15:02:20
4   2014-12-25 16:08:10
5   2014-12-31 23:44:12
6   2015-02-16 01:13:01
7   2015-02-16 15:00:13
8   2015-03-01 23:30:27
9   2015-04-18 16:34:29
10  2015-05-03 22:38:55
11  2015-06-05 21:43:36
12  2015-06-17 22:46:21
13  2015-06-29 00:07:01
14  2015-07-04 22:54:50
15  2015-07-18 22:02:45
16  2015-08-09 22:36:17
17  2015-09-11 00:24:15
18  2015-10-03 23:50:00
19  2015-10-24 23:05:09
20  2015-10-31 22:35:27
21  2015-11-07 22:10:52
22  2015-12-31 14:55:55
23  2016-01-20 21:53:38
24  2016-03-05 19:17:50
25  2016-03-25 15:55:07
26  2016-03-26 16:15:27
27  2016-07-14 23:14:31
28  2016-07-19 23:16:41
29  2016-07-29 22:12:44
30  2016-08-04 16:25:20
... ...                
58  2018-07-07 22:10:30
59  2018-07-14 23:25:01
60  2018-07-22 23:51:27
61  2018-08-12 16:03:42
62  2018-09-16 23:34:44
63  2018-09-20 23:42:05
64  2018-09-25 16:27:03
65  2018-09-29 23:36:45
66  2018-10-27 18:39:42
67  2018-11-17 16:33:50
68  2018-12-21 23:03:12
69  2018-12-29 15:41:39
70  2019-02-24 22:52:34
71  2019-03-02 23:45:09
72  2019-03-28 18:53:08
73  2019-04-14 00:38:27
74  2019-04-14 00:54:01
75  2019-04-17 21:50:56
76  2019-05-03 23:22:31
77  2019-05-05 22:28:44
78  2019-11-07 23:35:41
79  2019-12-21 00:39:17
80  2019-12-24 18:30:54
81  2020-01-01 23:20:58
82  2020-01-10 00:34:27
83  2020-01-10 23:45:10
84  2020-01-22 23:23:07
85  2020-01-26 17:39:44
86  2020-05-16 22:48:15
87  2020-06-16 14:36:21

Visto que temos uma data em branco vamos verificar qual é o registro afetado:

In [12]:
dados %>% filter(Scan.date=="")

Winery           Wine.name  Vintage Region      Country    
1 Goldridge Estate Pinot Noir 2011    Marlborough New Zealand
  Regional.wine.style    Average.rating Scan.date Your.rating Wine.type
1 New Zealand Pinot Noir 3.3                      1.5         Red Wine 
  Link.to.wine                         Label.image
1 https://www.vivino.com/wines/1741900

Verifiquei que a data está preenchida no Vivino, apesar de não estar nos dados que baixei: 28 de agosto de 2015. Em seguida realizei a correção do registro:

In [13]:
dados$Scan.date <- as.character(dados$Scan.date)

dados <- dados %>%
  mutate(Scan.date=replace(Scan.date,which(Scan.date==""),"2015-08-28 00:00:00"))


Por fim vamos salvar os dados em um arquivo csv para dar início ao trabalho no Tableau, já que as variáveis que potencialmente tem mais impacto foram saneadas:

In [ ]:
write.csv(dados,"vinhos_vivino_jun_20.csv")

Caso você queira ver como ficou o dashboard no Tableau, basta accessá-lo no link:
- https://public.tableau.com/profile/debora.coutinho#!/vizhome/Vivino_dashboard/VivinoDashboard?publish=yes